close all, clear, clc
I = double(imread("lena.jpg"));
%I= imread("bruit_gaussien_lena.jpg");
s=20;
I_bruit = gaussian_noise(I,s);
colormap gray;
imagesc(I_bruit);
alpha = 1;
n = 50;
deltaT = 1;
sigma1 = 1;
Y = perona_malik_enhancement(I_bruit, alpha, deltaT, sigma1, n);
figure(2);
colormap gray;
imagesc(Y);
sigma2 = 3;
Y = perona_malik_enhancement(I_bruit, alpha, deltaT, sigma2, n);
figure(3);
colormap gray;
imagesc(Y);
sigma3 = 10;
Y = perona_malik_enhancement(I_bruit, alpha, deltaT, sigma3, n);
figure(4);
colormap gray;
imagesc(Y);
sigma4 = 15;
Y = perona_malik_enhancement(I_bruit, alpha, deltaT, sigma4, n);
figure(5);
colormap gray;
imagesc(Y);
